name: Build and Release MyProxy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Icon.png
      run: |
        python -c "from PIL import Image
        img = Image.new('RGB', (100, 100), color = (73, 109, 137))
        img.save('Icon.png')"

    - name: Install fyne-cross
      run: |
        go get fyne.io/tools/cmd/fyne-cross

    - name: Build for Windows, Linux, and macOS
      run: |
        fyne-cross windows -app-id com.lucastq.myproxy
        fyne-cross linux -app-id com.lucastq.myproxy
        fyne-cross mac -app-id com.lucastq.myproxy

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MyProxy Builds
        path: builds/*

    - name: Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag: release-${{ github.run_id }}
        files: builds/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
